#!/bin/sh
set -e
set -x 

cd ${HOME}
python current/manage.py syncdb --noinput
# Only first time
# python /home/dotcloud/current/mkadmin.py

# Add send_tweet to crontab
echo "*/15 * * * * /home/dotcloud/current/send_tweet.sh" | crontab
