// Generated by CoffeeScript 1.6.3
/*
    Serialize Anything - MasterGED
    (c) 2013 Moreno Cunha, Domob / MasterVig
*/


(function() {
  jQuery.prototype.values = function(data) {
    var inps;
    inps = jQuery(this).find(":input").get();
    if (typeof data !== "object") {
      data = {};
      jQuery.each(inps, function() {
        if (this.name && (this.checked || /select|textarea/i.test(this.nodeName) || /text|hidden|password/i.test(this.type))) {
          return data[this.name] = jQuery(this).val();
        }
      });
      return data;
    } else {
      jQuery.each(inps, function() {
        if (this.name && data[this.name]) {
          if (this.type === "checkbox" || this.type === "radio") {
            return jQuery(this).prop("checked", data[this.name] === jQuery(this).val());
          } else {
            return jQuery(this).val(data[this.name]);
          }
        } else if (this.type === "checkbox") {
          return jQuery(this).prop("checked", false);
        }
      });
      return jQuery(this);
    }
  };

}).call(this);
