// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function() {
    var make_search, searchXHR;
    searchXHR = null;
    make_search = function() {
      var $pesq_ponto, key_search, source,
        _this = this;
      $pesq_ponto = $('#pesq_ponto');
      $pesq_ponto.css('border-color', '#CCC');
      key_search = $pesq_ponto.val();
      if (!key_search) {
        $pesq_ponto.css('border-color', '#FC4C4C');
        return;
      }
      source = $('#pesq_resultado').html();
      if (searchXHR) {
        searchXHR.abort();
      }
      return searchXHR = $.getJSON("/localizar/" + key_search + "/", function(pontos) {
        var context, i, obj, results, template, _i, _ref, _results;
        results = pontos.data.length;
        if (results > 50) {
          results = 50;
        }
        _results = [];
        for (i = _i = 0, _ref = results - 1; _i <= _ref; i = _i += 1) {
          obj = pontos.data[i];
          template = Handlebars.compile(source);
          context = {
            ponto: obj.ponto,
            lograd: obj.logradouro,
            bairro: obj.bairro,
            p_refer: obj.referencia
          };
          _results.push($('.lista_resultados').append(template(context)));
        }
        return _results;
      });
    };
    $('#pesq_button').bind('click', function(e) {
      return make_search();
    });
    $("#pesq_ponto").bind('keypress', function(e) {
      if (e.which === 13) {
        e.preventDefault();
        return make_search();
      }
    });
    return $(".resultado").live('click', function(e) {
      var url;
      url = "/registro/" + ($(this).attr('id')) + "/ponto/";
      return $(location).attr('href', url);
    });
  });

}).call(this);
