#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

PYTHON="$OPENSHIFT_HOMEDIR"python-2.7/virtenv/bin/python

echo "Executing 'python $OPENSHIFT_REPO_DIRwsgi/openshift/manage.py syncdb --noinput'"
$PYTHON "$OPENSHIFT_REPO_DIR"wsgi/openshift/manage.py syncdb --migrate --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIRwsgi/openshift/manage.py collectstatic --noinput'"
$PYTHON "$OPENSHIFT_REPO_DIR"wsgi/openshift/manage.py collectstatic --noinput

cd "$OPENSHIFT_HOMEDIR"python-2.6/repo/wsgi/static/
ln -s "$OPENSHIFT_HOMEDIR"python-2.6/repo/wsgi/openshift/media media
