// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function() {
    var make_search,
      _this = this;
    make_search = function() {
      var key_search, source,
        _this = this;
      key_search = $('#pesq_ponto').val();
      source = $('#pesq_resultado').html();
      return $.getJSON('/localizar/' + key_search + '/', function(pontos) {
        var context, i, obj, results, template, _i, _results;
        results = pontos.data.length;
        if (results > 50) {
          results = 50;
        }
        _results = [];
        for (i = _i = 1; _i <= results; i = _i += 1) {
          obj = pontos.data[i];
          console.log(i);
          console.log(obj);
          template = Handlebars.compile(source);
          context = {
            ponto: obj.ponto,
            lograd: obj.logradouro,
            bairro: obj.bairro,
            p_refer: obj.referencia
          };
          _results.push($('.lista_resultados').append(template(context)));
        }
        return _results;
      });
    };
    $('#pesq_button').bind('click', function(e) {
      return make_search();
    });
    $("#pesq_ponto").bind('keypress', function(e) {
      if (e.which === 13) {
        e.preventDefault();
        return make_search();
      }
    });
    $(".resultado").bind('click', function(e) {
      console.log($(this).attr('id'));
      var url;
      url = '/registro/' + $(this).attr('id');
      return $(location).attr('href', url);
    });
  });

}).call(this);
